// Define the number of display devices we have in the chain
#define MAX_DEVICES       16          // number of LED display blocks 8*8

//                       "0         1         2         3         4         5 "
//                       "0123456789012345678901234567890123456789012345678901"

// Default welcome message (att: size max. 52 !)
#define WELCOME          "Air quality display."
#define WELCOME2         "InfluencAir display."

// Default content for storage locations in CFG 
#define LOCATION_NAME_0  "Dilbeek - Regina Caeli"
#define LOCATION_NAME_1  "Anderlecht-Poincarélaan"
#define LOCATION_NAME_2  "" 
#define LOCATION_NAME_3  "" 
#define LOCATION_NAME_4  "" 
#define LOCATION_NAME_5  "" 
#define LOCATION_NAME_6  "" 
#define LOCATION_NAME_7  "" 
#define LOCATION_NAME_8  "" 
#define LOCATION_NAME_9  "" 
#define LOCATION_NAME_10 "" 
#define LOCATION_NAME_11 "" 
#define LOCATION_NAME_12 ""
#define LOCATION_NAME_13 "" 
#define LOCATION_NAME_14 "" 
#define LOCATION_NAME_15 "" 
#define LOCATION_NAME_16 "" 
#define LOCATION_NAME_17 "" 
#define LOCATION_NAME_18 "" 
#define LOCATION_NAME_19 "" 
#define LOCATION_NAME_20 "" 
#define LOCATION_NAME_21 "" 
#define LOCATION_NAME_22 "" 
#define LOCATION_NAME_23 "" 
#define LOCATION_NAME_24 "" 
#define LOCATION_NAME_25 "" 
#define LOCATION_NAME_26 "" 
#define LOCATION_NAME_27 "" 
#define LOCATION_NAME_28 "" 
#define LOCATION_NAME_29 "" 
#define LOCATION_NAME_30 "" 
#define LOCATION_NAME_31 "" 
//
#define SENSOR_API_1_0   "23288"
#define SENSOR_API_1_1   "63847"
#define SENSOR_API_1_2   ""
#define SENSOR_API_1_3   ""
#define SENSOR_API_1_4   ""
#define SENSOR_API_1_5   ""
#define SENSOR_API_1_6   ""
#define SENSOR_API_1_7   ""
#define SENSOR_API_1_8   ""
#define SENSOR_API_1_9   ""
#define SENSOR_API_1_10  ""
#define SENSOR_API_1_11  ""
#define SENSOR_API_1_12  ""
#define SENSOR_API_1_13  ""
#define SENSOR_API_1_14  ""
#define SENSOR_API_1_15  ""
#define SENSOR_API_1_16  "" 
#define SENSOR_API_1_17  "" 
#define SENSOR_API_1_18  ""
#define SENSOR_API_1_19  ""
#define SENSOR_API_1_20  ""
#define SENSOR_API_1_21  "" 
#define SENSOR_API_1_22  ""
#define SENSOR_API_1_23  ""
#define SENSOR_API_1_24  ""
#define SENSOR_API_1_25  "" 
#define SENSOR_API_1_26  ""
#define SENSOR_API_1_27  ""
#define SENSOR_API_1_28  ""
#define SENSOR_API_1_29  ""
#define SENSOR_API_1_30  ""
#define SENSOR_API_1_31  ""
//
#define SENSOR_API_2_0   "23289"
#define SENSOR_API_2_1   "63848"
#define SENSOR_API_2_2   ""
#define SENSOR_API_2_3   ""
#define SENSOR_API_2_4   ""
#define SENSOR_API_2_5   ""
#define SENSOR_API_2_6   "" 
#define SENSOR_API_2_7   ""
#define SENSOR_API_2_8   ""
#define SENSOR_API_2_9   ""
#define SENSOR_API_2_10  ""
#define SENSOR_API_2_11  ""
#define SENSOR_API_2_12  ""
#define SENSOR_API_2_13  ""
#define SENSOR_API_2_14  ""
#define SENSOR_API_2_15  ""
#define SENSOR_API_2_16  ""
#define SENSOR_API_2_17  ""
#define SENSOR_API_2_18  ""
#define SENSOR_API_2_19  ""
#define SENSOR_API_2_20  ""
#define SENSOR_API_2_21  ""
#define SENSOR_API_2_22  ""
#define SENSOR_API_2_23  ""
#define SENSOR_API_2_24  ""
#define SENSOR_API_2_25  ""
#define SENSOR_API_2_26  ""
#define SENSOR_API_2_27  ""
#define SENSOR_API_2_28  ""
#define SENSOR_API_2_29  ""
#define SENSOR_API_2_30  ""
#define SENSOR_API_2_31  ""
//
#define SENSOR_API_3_0   "82857"      // DNMS - Lat=47.774 Long=9.62 Alt=485.3 DE
#define SENSOR_API_3_1   ""
#define SENSOR_API_3_2   ""
#define SENSOR_API_3_3   ""
#define SENSOR_API_3_4   ""
#define SENSOR_API_3_5   ""
#define SENSOR_API_3_6   ""
#define SENSOR_API_3_7   ""
#define SENSOR_API_3_8   ""
#define SENSOR_API_3_9   ""
#define SENSOR_API_3_10  ""
#define SENSOR_API_3_11  ""
#define SENSOR_API_3_12  ""
#define SENSOR_API_3_13  ""
#define SENSOR_API_3_14  "" 
#define SENSOR_API_3_15  ""
#define SENSOR_API_3_16  ""
#define SENSOR_API_3_17  ""
#define SENSOR_API_3_18  ""
#define SENSOR_API_3_19  ""
#define SENSOR_API_3_20  ""
#define SENSOR_API_3_21  ""
#define SENSOR_API_3_22  ""
#define SENSOR_API_3_23  ""
#define SENSOR_API_3_24  ""
#define SENSOR_API_3_25  ""
#define SENSOR_API_3_26  ""
#define SENSOR_API_3_27  ""
#define SENSOR_API_3_28  ""
#define SENSOR_API_3_29  ""
#define SENSOR_API_3_30  ""
#define SENSOR_API_3_31  ""
//
#define SENSOR_API_4_0   "9000004259"  // Telraam Regina Caeli Dilbeek
#define SENSOR_API_4_1   ""
#define SENSOR_API_4_2   ""
#define SENSOR_API_4_3   ""
#define SENSOR_API_4_4   ""
#define SENSOR_API_4_5   ""
#define SENSOR_API_4_6   ""
#define SENSOR_API_4_7   ""
#define SENSOR_API_4_8   ""
#define SENSOR_API_4_9   ""
#define SENSOR_API_4_10  ""
#define SENSOR_API_4_11  ""
#define SENSOR_API_4_12  ""
#define SENSOR_API_4_13  ""
#define SENSOR_API_4_14  ""
#define SENSOR_API_4_15  ""
#define SENSOR_API_4_16  ""
#define SENSOR_API_4_17  ""
#define SENSOR_API_4_18  ""
#define SENSOR_API_4_19  ""
#define SENSOR_API_4_20  ""
#define SENSOR_API_4_21  ""
#define SENSOR_API_4_22  ""
#define SENSOR_API_4_23  ""
#define SENSOR_API_4_24  ""
#define SENSOR_API_4_25  ""
#define SENSOR_API_4_26  ""
#define SENSOR_API_4_27  ""
#define SENSOR_API_4_28  ""
#define SENSOR_API_4_29  ""
#define SENSOR_API_4_30  ""
#define SENSOR_API_4_31  ""
